# Generated by Django 5.1.2 on 2024-10-21 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coord_x', models.FloatField()),
                ('coord_y', models.FloatField()),
                ('cur_bio', models.FloatField(default=0.0)),
                ('cur_glass', models.FloatField(default=0.0)),
                ('cur_plastic', models.FloatField(default=0.0)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coord_x', models.FloatField()),
                ('coord_y', models.FloatField()),
                ('cur_bio', models.FloatField(default=0.0)),
                ('cur_glass', models.FloatField(default=0.0)),
                ('cur_plastic', models.FloatField(default=0.0)),
                ('name', models.CharField(max_length=200)),
                ('max_bio', models.FloatField()),
                ('max_glass', models.FloatField()),
                ('max_plastic', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
