# Generated by Django 5.1.2 on 2024-10-27 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waste_type', models.CharField(max_length=30)),
                ('waste_amount', models.FloatField()),
                ('organization_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eco.organization')),
            ],
        ),
    ]
